---
version: "3"
services:
 devopsdb:
   image: thammisettivamsi/newrepo:dbimg
   ports:
     - "3306:3306"

 application:
   image: thammisettivamsi/newrepo:appimg
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
